/*
==========================================================
TOOLXONE BASIC CALCULATOR
----------------------------------------------------------
Features
--------
- Accurate arithmetic calculations
- Formatted number display
- Number-to-words results
- Keyboard support
- Safe operator handling
- Decimal validation
- Statistics integration
==========================================================
*/

let justCalculated = false;
let rawExpression = "";


/* =====================================================
   1. APPEND VALUE
   ===================================================== */

function appendValue(value) {
    const operators = [
        "+",
        "-",
        "*",
        "/"
    ];

    if (justCalculated) {
        if (operators.includes(value)) {
            justCalculated = false;
        } else if (
            isDigit(value) ||
            value === "."
        ) {
            rawExpression = "";
            justCalculated = false;
        }
    }

    if (operators.includes(value)) {
        appendOperator(value);
    } else {
        appendNumberCharacter(value);
    }

    updateDisplay();
}


/* =====================================================
   2. NUMBER INPUT
   ===================================================== */

function appendNumberCharacter(value) {

    if (value === ".") {

        if (currentNumberHasDecimal()) {
            return;
        }

        /*
         * Convert:
         * .5     → 0.5
         * 5+.2   → 5+0.2
         */
        if (
            !rawExpression ||
            isOperator(
                rawExpression.slice(-1)
            )
        ) {
            rawExpression += "0.";
        } else {
            rawExpression += ".";
        }

        clearNumberWords();
        return;
    }

    if (!isDigit(value)) {
        return;
    }

    rawExpression += value;

    clearNumberWords();
}


/* =====================================================
   3. OPERATOR INPUT
   ===================================================== */

function appendOperator(operator) {

    if (!isOperator(operator)) {
        return;
    }

    if (!rawExpression) {

        /*
         * Allow a negative starting number.
         */
        if (operator === "-") {
            rawExpression = "-";
        }

        return;
    }

    /*
     * A lone minus is not yet a complete number.
     */
    if (rawExpression === "-") {
        return;
    }

    const lastCharacter =
        rawExpression.slice(-1);

    /*
     * Replace the previous operator rather than
     * creating malformed expressions such as:
     *
     * 5++2
     * 8/*2
     * 10+-+3
     */
    if (isOperator(lastCharacter)) {
        rawExpression =
            rawExpression.slice(0, -1) +
            operator;
    } else if (lastCharacter === ".") {

        /*
         * Complete a trailing decimal:
         * 5. +  → 5.0+
         */
        rawExpression += "0" + operator;

    } else {
        rawExpression += operator;
    }

    clearNumberWords();
}


/* =====================================================
   4. CLEAR
   ===================================================== */

function clearDisplay() {
    rawExpression = "";
    justCalculated = false;

    updateDisplay();
    clearNumberWords();
}


/* =====================================================
   5. BACKSPACE
   ===================================================== */

function deleteLastCharacter() {

    rawExpression =
        rawExpression.slice(0, -1);

    justCalculated = false;

    updateDisplay();
    clearNumberWords();
}


/* =====================================================
   6. CALCULATE
   ===================================================== */

function calculate() {

    const display =
        document.getElementById("display");

    if (
        !display ||
        !rawExpression
    ) {
        return;
    }

    /*
     * A lone negative sign is not calculable.
     */
    if (rawExpression === "-") {
        return;
    }

    const lastCharacter =
        rawExpression.slice(-1);

    /*
     * Do not calculate incomplete expressions.
     */
    if (
        isOperator(lastCharacter) ||
        lastCharacter === "."
    ) {
        return;
    }

    /*
     * Defense-in-depth:
     * expression may contain only calculator
     * characters generated by this interface.
     */
    if (
        !/^-?[\d.+*/-]+$/.test(
            rawExpression
        )
    ) {
        showCalculatorError();
        return;
    }

    try {

        const result =
            Function(
                `"use strict"; return (${rawExpression});`
            )();

        if (!Number.isFinite(result)) {
            throw new Error(
                "Invalid calculation result."
            );
        }

        rawExpression =
            normalizeResult(result);

        display.value =
            formatExpression(
                rawExpression
            );

        showNumberWords(Number(rawExpression));

        /*
         * Record only successful calculations.
         */
        if (
            window.ToolXoneStatisticsEvents &&
            typeof ToolXoneStatisticsEvents
                .recordCalculation === "function"
        ) {
            ToolXoneStatisticsEvents
                .recordCalculation(
                    "basic-calculator"
                );
        }

        justCalculated = true;

    } catch (error) {

        showCalculatorError();

        console.error(
            "Calculator error:",
            error
        );
    }
}


/* =====================================================
   7. ERROR STATE
   ===================================================== */

function showCalculatorError() {

    const display =
        document.getElementById("display");

    if (display) {
        display.value = "Error";
    }

    rawExpression = "";
    justCalculated = true;

    clearNumberWords();
}


/* =====================================================
   8. DISPLAY FORMATTING
   ===================================================== */

function updateDisplay() {
    const display =
        document.getElementById(
            "display"
        );

    display.value =
        rawExpression
            ? formatExpression(rawExpression)
            : "0";
}


function formatExpression(expression) {

    if (!expression) {
        return "";
    }

    /*
     * Preserve a leading negative sign while
     * formatting individual numeric components.
     */
    const leadingNegative =
        expression.startsWith("-");

    const workingExpression =
        leadingNegative
            ? expression.slice(1)
            : expression;

    const formatted =
        workingExpression
            .split(/([+\-*/])/)
            .map(part => {

                if (
                    !part ||
                    isOperator(part)
                ) {
                    return part;
                }

                return formatNumberPart(
                    part
                );
            })
            .join("");

    return leadingNegative
        ? "-" + formatted
        : formatted;
}


function formatNumberPart(value) {

    if (
        value === "." ||
        value === "-"
    ) {
        return value;
    }

    const hasTrailingDecimal =
        value.endsWith(".");

    const [
        integerPart,
        decimalPart
    ] = value.split(".");

    const formattedInteger =
        formatIntegerString(
            integerPart
        );

    if (hasTrailingDecimal) {
        return `${formattedInteger}.`;
    }

    if (decimalPart !== undefined) {
        return (
            `${formattedInteger}.` +
            decimalPart
        );
    }

    return formattedInteger;
}


function formatIntegerString(value) {

    const sign =
        value.startsWith("-")
            ? "-"
            : "";

    const digits =
        value.replace("-", "");

    if (!digits) {
        return sign;
    }

    const formatted =
        digits.replace(
            /\B(?=(\d{3})+(?!\d))/g,
            ","
        );

    return sign + formatted;
}


/* =====================================================
   9. NUMBER WORDS
   ===================================================== */

function showNumberWords(value) {

    const wordsElement =
        document.getElementById(
            "numberWords"
        );

    if (!wordsElement) {
        return;
    }

    if (!window.ToolXoneNumberEngine) {
        wordsElement.textContent = "";
        wordsElement.hidden = true;
        return;
    }

    wordsElement.textContent =
        ToolXoneNumberEngine.words(
            value
        );

    wordsElement.hidden =
        !wordsElement.textContent;
}


function clearNumberWords() {

    const wordsElement =
        document.getElementById(
            "numberWords"
        );

    if (!wordsElement) {
        return;
    }

    wordsElement.textContent = "";
    wordsElement.hidden = true;
}


/* =====================================================
   10. HELPERS
   ===================================================== */

function isDigit(value) {
    return /^\d$/.test(
        String(value)
    );
}


function isOperator(value) {
    return [
        "+",
        "-",
        "*",
        "/"
    ].includes(value);
}


function currentNumberHasDecimal() {

    const parts =
        rawExpression.split(
            /[+\-*/]/
        );

    const currentNumber =
        parts[
            parts.length - 1
        ] || "";

    return currentNumber.includes(".");
}


function normalizeResult(value) {

    /*
     * Reduce floating-point artifacts such as:
     *
     * 0.1 + 0.2
     * 0.30000000000000004
     *
     * while preserving useful precision.
     */
    return String(
        Number(
            value.toPrecision(15)
        )
    );
}


/* =====================================================
   11. KEYBOARD SUPPORT
   ===================================================== */

document.addEventListener(
    "keydown",
    function (event) {

        /*
         * Do not intercept keyboard input while
         * the visitor is typing into another
         * editable field on the page.
         */
        const target =
            event.target;

        const isEditable =
            target &&
            (
                target.tagName === "TEXTAREA" ||
                target.tagName === "SELECT" ||
                (
                    target.tagName === "INPUT" &&
                    target.id !== "display"
                ) ||
                target.isContentEditable
            );

        if (isEditable) {
            return;
        }

        if (isDigit(event.key)) {

            event.preventDefault();

            appendValue(
                event.key
            );

            return;
        }

        if (
            [
                "+",
                "-",
                "*",
                "/",
                "."
            ].includes(event.key)
        ) {

            event.preventDefault();

            appendValue(
                event.key
            );

            return;
        }

        if (
            event.key === "Enter" ||
            event.key === "="
        ) {

            event.preventDefault();

            calculate();

            return;
        }

        if (event.key === "Backspace") {

            event.preventDefault();

            deleteLastCharacter();

            return;
        }

        if (
            event.key === "Delete" ||
            event.key === "Escape"
        ) {

            event.preventDefault();

            clearDisplay();
        }
    }
);


/* =====================================================
   12. INITIAL STATE
   ===================================================== */

document.addEventListener(
    "DOMContentLoaded",
    function () {
        updateDisplay();
        clearNumberWords();
    }
);